print('Sinais aritméticos:')
print('+ = soma')
print('- = subtração')
print('* = multiplicação')
print('/ = divisão')
print('// = divisão inteira (trás apenas o resultado da divisão inteira, ou seja, arredondado.)')
print('** = exponenciação')
print('% = retorna o resto da divisão entre um número e outro.')
print('() = altera a precedência das contas, conforme matemática normal.')
print('Se colocar string para fazer contas, vai retornar erro.;')
print('Se colocar um número inteiro * uma string, ele vai retornar a repetição da string.')
print('Se colocar duas strings sendo somadas, ele vai retornar a concatenação, ou seja, juntar os dois resultados.')

print('Exercícios')

print('Adição: 10 + 10 =', 10+10)
print('Subtração: 10 - 5 =', 10-5)
print('Multiplicação: 10*10 =', 10*10)
print('Divisão: 10/3 =', 10/3)
print('Divisão Inteira: 10//3 =', 10//3)
print('Exponenciação: 2**2 =', 2**2)
print('Resto da divisão: 10%3 =', 10%3)
print('Parênteses: (5+2)*10 =', (5+2)*10)
print(5*'Robson ama Taynara')
print('Robson'+' '+'ama'+' '+'Taynara')

